### ISSUE TITLE
JTAppleCalendar installation issue

### ISSUE THREAD

**Issue by oyapici** [agustinoromo/calendar-iOS#1]
Hello,
I installed JTAppleCalendar modifying  Podfile with following codes : 

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Appt' do
    pod 'JTAppleCalendar', '~> 7.0'
end

But, I encounter "No such module 'JTAppleCalendar'" error message on import JTAppleCalendar on CalendarDayCell.swift file.   

Do you have a recommendation how to add JTAppleCalendar to the project ?

Best regards.

**Comment by a-mromo** [comment]
Hi @oyapici, I believe this is a common error message with many pods.
Most of the times I just Build and Run the project and the error message is removed.

Have you tried doing a clean?, you can find it under Product/Clean in the menu bar
I installed JTLAppleCalendar through Cocoapods. You probably already done this but, please make sure you open the .xcworkspace file.

Let me know if you still having issues.

**Comment by oyapici** [comment]
Hi,
Product/clean solved the issue, thank you.  Now I have 297 swift compile errors.  I changed Swift Language Version from 4.0 to 3.2 but it didn't work.

Thank you

**Comment by oyapici** [comment]
I tried again from the beginning.  Now, I don't have errors.  Sorry for inconvenience.

**Comment by a-mromo** [comment]
@oyapici Awesome! Good to hear that a clean solved the problem. 

I wanted to let you know that this was my first project project as an iOS developer so there is plenty of room for improvement. Will push some updates on Core Data soon.
